enter correct score for question 1:1
enter correct score for question 2:1
enter correct score for question 3:1
enter correct score for question 4:0
enter correct score for question 5:0
enter correct score for question 6:1
enter correct score for question 7:0
enter correct score for question 8:0
enter correct score for question 9:1
enter correct score for question 10:0
enter correct score for question 11:0
enter correct score for question 12:1
enter correct score for question 13:1
enter correct score for question 14:1
